on:
    release:
        types:
          - published

name: Build and Publish Docker Image

permissions:
    contents: read
    packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
        run: rm -rf /opt/hostedtoolcache
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Build image
        run: docker buildx build -t pipeline_build --file ./Dockerfile . --platform linux/amd64 --load # Ticket 133 to enable multi-architecture builds (linux/arm64)
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          RELEASE_TAG=$(echo $GITHUB_REF | cut -d / -f 3)
          docker tag pipeline_build $IMAGE_ID:$RELEASE_TAG
          docker push $IMAGE_ID:$RELEASE_TAG
